import warnings
from flask import Flask, jsonify, render_template, request
import numpy as np
import joblib
from flask_cors import CORS
from flask_cors import CORS, cross_origin

app = Flask(__name__)
CORS(app, supports_credentials= True)
app.config["CORS_HEADERS"] = "Content-Type" #

warnings.filterwarnings("ignore", category=UserWarning, message="Trying to unpickle estimator GaussianNB from version 1.1.1 when using version 1.5.1")

cluster_1 =[
    "panic disorder",
    "poisoning due to ethylene glycol",
    "sick sinus syndrome",
    "eating disorder",
    "transient ischemic attack",
    "subdural hemorrhage",
    "fetal alcohol syndrome",
    "emphysema",
    "cysticercosis",
    "substance-related mental disorder",
    "postpartum depression",
    "coronary atherosclerosis",
    "lung contusion",
    "hypertrophic obstructive cardiomyopathy (hocm)",
    "normal pressure hydrocephalus",
    "hyperkalemia",
    "abscess of the lung",
    "volvulus",
    "poisoning due to analgesics",
    "atrial fibrillation",
    "achalasia",
    "marijuana abuse",
    "cryptococcosis",
    "pulmonary congestion",
    "tuberous sclerosis",
    "chronic obstructive pulmonary disease (copd)",
    "open wound of the back",
    "heart block",
    "magnesium deficiency",
    "pericarditis",
    "attention deficit hyperactivity disorder (adhd)",
    "pulmonic valve disease",
    "tietze syndrome",
    "conversion disorder",
    "primary insomnia",
    "chronic kidney disease",
    "amyloidosis",
    "poisoning due to antimicrobial drugs",
    "myasthenia gravis",
    "hypoglycemia",
    "carbon monoxide poisoning",
    "panic attack",
    "polymyalgia rheumatica",
    "acute bronchospasm",
    "huntington disease",
    "anemia due to chronic kidney disease",
    "insulin overdose",
    "premenstrual tension syndrome",
    "hepatic encephalopathy",
    "pulmonary fibrosis",
    "mitral valve disease",
    "drug abuse (opioids)",
    "acute kidney injury",
    "intracranial abscess",
    "drug abuse (methamphetamine)",
    "poisoning due to antihypertensives",
    "tension headache",
    "narcolepsy",
    "anxiety",
    "impulse control disorder",
    "drug reaction",
    "chronic rheumatic fever",
    "hypocalcemia",
    "pneumonia",
    "premature ventricular contractions (pvcs)",
    "testicular cancer",
    "hydrocephalus",
    "anemia due to malignancy",
    "parathyroid adenoma",
    "glucocorticoid deficiency",
    "autism",
    "drug withdrawal",
    "hypercholesterolemia",
    "kidney failure",
    "dysthymic disorder",
    "hypertensive heart disease",
    "drug abuse (barbiturates)",
    "alcohol withdrawal",
    "premature atrial contractions (pacs)",
    "meningioma",
    "lung cancer",
    "benign paroxysmal positional vertical (bppv)",
    "sarcoidosis",
    "aspergillosis",
    "subacute thyroiditis",
    "intracerebral hemorrhage",
    "alzheimer disease",
    "atrial flutter",
    "heart attack",
    "orthostatic hypotension",
    "obstructive sleep apnea (osa)",
    "hypokalemia",
    "hypernatremia",
    "tricuspid valve disease",
    "dementia",
    "paroxysmal ventricular tachycardia",
    "poisoning due to gas",
    "central atherosclerosis",
    "wernicke korsakoff syndrome",
    "acute bronchitis",
    "myocarditis",
    "ischemic heart disease",
    "lyme disease",
    "acute respiratory distress syndrome (ards)",
    "toxic multinodular goiter",
    "anemia",
    "central retinal artery or vein occlusion",
    "paroxysmal supraventricular tachycardia",
    "drug abuse",
    "pulmonary hypertension",
    "aortic valve disease",
    "hypothermia",
    "lewy body dementia",
    "ascending cholangitis",
    "somatization disorder",
    "schizophrenia",
    "endocarditis",
    "sepsis",
    "cardiac arrest",
    "cardiomyopathy",
    "social phobia",
    "fracture of the skull",
    "tracheitis",
    "post-traumatic stress disorder (ptsd)",
    "sinus bradycardia",
    "tic (movement) disorder",
    "adrenal adenoma",
    "esophagitis",
    "drug poisoning due to medication",
    "moyamoya disease",
    "heat exhaustion",
    "psychotic disorder",
    "smoking or tobacco addiction",
    "pneumothorax",
    "lactose intolerance",
    "graves disease",
    "dissociative disorder",
    "epidural hemorrhage",
    "pleural effusion",
    "arrhythmia",
    "poisoning due to antipsychotics",
    "birth trauma",
    "pneumoconiosis",
    "angina",
    "factitious disorder",
    "galactorrhea of unknown cause",
    "diabetic ketoacidosis",
    "obsessive compulsive disorder (ocd)",
    "hyponatremia",
    "personality disorder",
    "spinocerebellar ataxia",
    "developmental disability",
    "acute stress reaction",
    "delirium",
    "rhabdomyolysis",
    "abdominal aortic aneurysm",
    "pulmonary embolism",
    "conduct disorder",
]
cluster_2 = [
    "vocal cord polyp",
    "cellulitis or abscess of mouth",
    "salivary gland disorder",
    "stroke",
    "intracranial hemorrhage",
    "conductive hearing loss",
    "cranial nerve palsy",
    "concussion",
    "hyperopia",
    "lymphedema",
    "foreign body in the ear",
    "parkinson disease",
    "myelodysplastic syndrome",
    "torticollis",
    "thyroid disease",
    "peritonsillar abscess",
    "head and neck cancer",
    "scarlet fever",
    "foreign body in the throat",
    "brain cancer",
    "hemochromatosis",
    "decubitus ulcer",
    "sensorineural hearing loss",
    "poisoning due to anticonvulsants",
    "presbyopia",
    "kidney disease due to longstanding hypertension",
    "amyotrophic lateral sclerosis (als)",
    "down syndrome",
    "fracture of the pelvis",
    "lichen simplex",
    "bone disorder",
    "epilepsy",
    "osteomyelitis",
    "intestinal cancer",
    "guillain barre syndrome",
    "poisoning due to opioids",
    "lichen planus"
]

cluster_3 = [
    "turner syndrome",
    "foreign body in the vagina",
    "restless leg syndrome",
    "presbyacusis",
    "poisoning due to antidepressants",
    "protein deficiency",
    "otosclerosis",
    "dislocation of the ankle",
    "poisoning due to sedatives",
    "hirschsprung disease",
    "omphalitis",
    "alcohol abuse",
    "anemia of chronic disease",
    "placental abruption",
    "vacterl syndrome",
    "atonic bladder",
    "cushing syndrome",
    "intussusception",
    "testicular torsion",
    "heart contusion",
    "dislocation of the wrist",
    "depression",
    "diabetes insipidus",
    "acute fatty liver of pregnancy (aflp)",
    "trichiasis",
    "acariasis",
    "g6pd enzyme deficiency",
    "toxoplasmosis",
    "kaposi sarcoma"
]

cluster_4 = [
    "cryptorchidism",
    "eye alignment disorder",
    "injury to the finger",
    "abdominal hernia",
    "cerebral palsy",
    "neonatal jaundice",
    "injury to the trunk",
    "hydrocele of the testicle",
    "dermatitis due to sun exposure",
    "pituitary disorder",
    "aplastic anemia",
    "primary kidney disease",
    "premature ovarian failure",
    "congenital heart defect",
    "benign prostatic hyperplasia (bph)",
    "congenital malformation syndrome",
    "varicocele of the testicles",
    "testicular disorder",
    "hormone disorder",
    "perirectal infection",
    "phimosis",
    "hematoma",
    "male genitalia infection",
    "epididymitis",
    "inguinal hernia"
]

cluster_5 = [
    "atrophic vaginitis",
    "vaginitis",
    "pyelonephritis",
    "uterine fibroids",
    "idiopathic nonmenstrual bleeding",
    "vaginal yeast infection",
    "endophthalmitis",
    "hemarthrosis",
    "pelvic organ prolapse",
    "coagulation (bleeding) disorder",
    "pinworm infection",
    "urethral valves",
    "bladder disorder",
    "polycystic kidney disease",
    "bladder cancer",
    "stress incontinence",
    "benign kidney cyst",
    "injury to internal organ",
    "cold sore",
    "vesicoureteral reflux",
    "gonorrhea",
    "vaginal cyst",
    "ectopic pregnancy",
    "kidney stone",
    "syphilis",
    "itching of unknown cause",
    "urge incontinence",
    "edward syndrome",
    "balanitis",
    "uterine atony",
    "pityriasis rosea",
    "cervicitis",
    "urethritis",
    "prostatitis",
    "urethral stricture",
    "tuberculosis",
    "endometrial hyperplasia",
    "menopause",
    "erectile dysfunction",
    "temporary or benign blood in urine",
    "urethral disorder",
    "psychosexual disorder",
    "trichomonas infection",
    "urinary tract obstruction",
    "ovarian cyst",
    "female genitalia infection",
    "spermatocele",
    "kidney cancer",
    "cystitis",
    "cervical cancer",
    "yeast infection",
    "atrophy of the corpus cavernosum",
    "idiopathic painful menstruation",
    "placenta previa",
    "vulvar disorder",
    "urinary tract infection",
    "prostate cancer",
    "carcinoid syndrome",
    "genital herpes",
    "hpv",
    "benign vaginal discharge (leukorrhea)",
    "cervical disorder",
    "dyshidrosis"
]

cluster_6 = [
    "fracture of the hand",
    "pyloric stenosis",
    "metabolic disorder",
    "fibromyalgia",
    "thrombophlebitis",
    "fracture of the arm",
    "bursitis",
    "spondylosis",
    "injury to the shoulder",
    "injury to the arm",
    "neuralgia",
    "degenerative disc disease",
    "fracture of the shoulder",
    "lateral epicondylitis (tennis elbow)",
    "open wound of the arm",
    "thoracic outlet syndrome",
    "dislocation of the shoulder",
    "vitamin d deficiency",
    "pain disorder affecting the neck",
    "primary immunodeficiency",
    "spinal stenosis",
    "lymphangitis",
    "hidradenitis suppurativa",
    "mononeuritis",
    "brachial neuritis",
    "sprain or strain",
    "adhesive capsulitis of the shoulder",
    "herniated disk",
    "mastectomy"
]

cluster_7 = [
    "headache after lumbar puncture",
    "problem during pregnancy",
    "atelectasis",
    "choledocholithiasis",
    "thoracic aortic aneurysm",
    "ischemia of the bowel",
    "peritonitis",
    "infectious gastroenteritis",
    "pituitary adenoma",
    "nonalcoholic liver disease (nash)",
    "vulvodynia",
    "chronic inflammatory demyelinating polyneuropathy (cidp)",
    "idiopathic absence of menstruation",
    "hiatal hernia",
    "hypercalcemia",
    "hydronephrosis",
    "diverticulosis",
    "syndrome of inappropriate secretion of adh (siadh)",
    "gastrointestinal hemorrhage",
    "adrenal cancer",
    "esophageal varices",
    "temporomandibular joint disorder",
    "hepatitis due to a toxin",
    "hemolytic anemia",
    "gastroparesis",
    "polycythemia vera",
    "encephalitis",
    "crohn disease",
    "fluid overload",
    "primary thrombocythemia",
    "hydatidiform mole",
    "pelvic fistula",
    "intestinal disease",
    "persistent vomiting of unknown cause",
    "pancreatic cancer",
    "iron deficiency anemia",
    "autonomic nervous system disorder",
    "dumping syndrome",
    "lymphadenitis",
    "migraine",
    "head injury",
    "hypovolemia",
    "heat stroke",
    "cholecystitis",
    "meningitis",
    "celiac disease",
    "chronic constipation",
    "essential tremor",
    "idiopathic infrequent menstruation",
    "fracture of the vertebra",
    "subarachnoid hemorrhage",
    "eustachian tube dysfunction (ear disorder)",
    "dislocation of the vertebra",
    "hyperemesis gravidarum",
    "gynecomastia",
    "trigeminal neuralgia",
    "peripheral nerve disorder",
    "cerebral edema",
    "chronic pancreatitis",
    "multiple sclerosis",
    "ulcerative colitis",
    "spondylolisthesis",
    "pseudotumor cerebri"
]

cluster_8 = [
    "osteochondrosis",
    "flat feet",
    "dislocation of the elbow",
    "bone spur of the calcaneous",
    "plantar fasciitis",
    "injury to the leg",
    "osteoarthritis",
    "carpal tunnel syndrome",
    "fracture of the neck",
    "joint effusion",
    "ankylosing spondylitis",
    "nerve impingement near the shoulder",
    "injury of the ankle",
    "fracture of the ankle"
]

cluster_9 = [
    "injury to the knee",
    "ingrown toe nail",
    "juvenile rheumatoid arthritis",
    "vasculitis",
    "dislocation of the patella",
    "gout",
    "envenomation from spider or animal bite",
    "osteochondroma",
    "ganglion cyst",
    "dislocation of the knee",
    "sporotrichosis",
    "open wound of the foot",
    "chondromalacia of the patella",
    "diabetic peripheral neuropathy",
    "scabies",
    "bunion",
    "burn",
    "avascular necrosis"
]

cluster_10 = [
    "tinnitus of unknown cause",
    "myositis",
    "mononucleosis",
    "extrapyramidal effect of drugs",
    "meniere disease",
    "pain after an operation",
    "lymphoma",
    "syringomyelia",
    "labyrinthitis",
    "pharyngitis",
    "ependymoma",
    "pinguecula",
    "muscle spasm",
    "optic neuritis",
    "hemiplegia",
    "seasonal allergies (hay fever)",
    "blepharospasm",
    "ileus",
    "noninfectious gastroenteritis",
    "preeclampsia",
    "croup",
    "iridocyclitis",
    "thyroid nodule",
    "malaria",
    "hypertension of pregnancy",
    "jaw disorder",
    "subconjunctival hemorrhage",
    "high blood pressure",
    "malignant hypertension",
    "open wound of the head",
    "nasal polyp",
    "shingles (herpes zoster)",
    "tourette syndrome",
    "strep throat",
    "aphthous ulcer",
    "rocky mountain spotted fever",
    "deviated nasal septum",
    "laryngitis"
]

cluster_11 = [
    "glaucoma",
    "diabetic retinopathy",
    "chalazion",
    "retinopathy due to high blood pressure",
    "corneal disorder",
    "cornea infection",
    "astigmatism",
    "chorioretinitis",
    "vitreous hemorrhage",
    "allergy",
    "acute glaucoma",
    "scleritis",
    "pterygium",
    "orbital cellulitis",
    "bell palsy",
    "conjunctivitis due to allergy",
    "myopia",
    "macular degeneration",
    "cat scratch disease",
    "chronic glaucoma",
    "retinal detachment",
    "open wound of the eye",
    "corneal abrasion",
    "cyst of the eyelid",
    "dry eye of unknown cause",
    "stye",
    "vitreous degeneration",
    "floaters",
    "cataract",
    "amblyopia",
    "uveitis",
    "blepharitis",
    "ectropion",
    "aphakia",
    "rheumatic fever",
    "conjunctivitis",
    "conjunctivitis due to virus"
]

cluster_12 = [
    "rotator cuff injury",
    "chronic pain disorder",
    "injury to the hand",
    "fracture of the finger",
    "fracture of the rib",
    "open wound of the shoulder",
    "overflow incontinence",
    "trigger finger (finger disorder)",
    "open wound of the finger",
    "open wound of the hand",
    "viral hepatitis"
]

cluster_13 = [
    "liver cancer",
    "cirrhosis",
    "injury to the abdomen",
    "induced abortion",
    "ovarian torsion",
    "intestinal malabsorption",
    "esophageal cancer",
    "colonic polyp",
    "endometriosis",
    "gastroesophageal reflux disease (gerd)",
    "anal fissure",
    "threatened pregnancy",
    "scurvy",
    "uterine cancer",
    "vaginismus",
    "open wound of the abdomen",
    "sickle cell crisis",
    "ovarian cancer",
    "intestinal obstruction",
    "neurofibromatosis",
    "idiopathic excessive menstruation",
    "irritable bowel syndrome",
    "chlamydia",
    "parasitic disease",
    "lipoma",
    "idiopathic irregular menstrual cycle",
    "liver disease",
    "gas gangrene",
    "diverticulitis",
    "appendicitis",
    "spontaneous abortion",
    "gallstone",
    "colorectal cancer",
    "soft tissue sarcoma",
    "gastritis",
    "stomach cancer",
    "premature rupture of amniotic membrane",
    "gastroduodenal ulcer",
    "white blood cell disease"
]

cluster_14 = [
    "injury to the hip",
    "spondylitis",
    "crushing injury",
    "empyema",
    "infection of open wound",
    "complex regional pain syndrome",
    "sciatica",
    "varicose veins",
    "bone cancer",
    "chronic knee pain",
    "fracture of the patella",
    "pseudohypoparathyroidism",
    "open wound of the knee",
    "vertebrobasilar insufficiency",
    "fracture of the leg",
    "insect bite",
    "pyogenic skin infection",
    "tendinitis",
    "venous insufficiency",
    "raynaud disease",
    "peripheral arterial embolism",
    "de quervain disease",
    "septic arthritis",
    "dislocation of the finger",
    "peripheral arterial disease",
    "necrotizing fasciitis",
    "paronychia"
]

cluster_15 = [
    "acute pancreatitis",
    "teething syndrome",
    "dislocation of the foot",
    "otitis media",
    "abscess of nose",
    "mittelschmerz",
    "rectal disorder",
    "whooping cough",
    "acute bronchiolitis",
    "viral exanthem",
    "neuropathy due to drugs",
    "pelvic inflammatory disease",
    "erythema multiforme",
    "lumbago",
    "chronic back pain",
    "diaper rash"
]

cluster_16 = [
    "asthma",
    "acute sinusitis",
    "pulmonary eosinophilia",
    "hyperhidrosis",
    "chronic sinusitis",
    "indigestion",
    "acute otitis media",
    "chronic otitis media",
    "open wound of the chest",
    "alcohol intoxication",
    "food allergy",
    "leukemia",
    "nose disorder",
    "drug abuse (cocaine)",
    "typhoid fever",
    "oral mucosal lesion",
    "folate deficiency",
    "oral thrush (yeast infection)",
    "allergy to animals",
    "abscess of the pharynx",
    "chickenpox",
    "common cold",
    "valley fever",
    "interstitial lung disease",
    "sickle cell anemia",
    "frostbite",
    "zenker diverticulum",
    "hyperlipidemia",
    "granuloma inguinale",
    "tonsillar hypertrophy",
    "heart failure",
    "breast infection (mastitis)",
    "mucositis"
]

cluster_17 = [
    "mastoiditis",
    "cholesteatoma",
    "lice",
    "muscular dystrophy",
    "trichinosis",
    "otitis externa (swimmer's ear)",
    "ear drum damage",
    "injury to the face",
    "impetigo",
    "conjunctivitis due to bacteria",
    "ear wax impaction",
    "foreign body in the nose",
    "open wound of the nose"
]
cluster_18 = [
    "foreign body in the gastrointestinal tract",
    "goiter",
    "connective tissue disorder",
    "stricture of the esophagus",
    "sjogren syndrome",
    "tonsillitis"
]

cluster_19 = [
    "viral warts",
    "pilonidal cyst",
    "open wound of the neck",
    "actinic keratosis",
    "deep vein thrombosis (dvt)",
    "oral leukoplakia",
    "open wound of the mouth",
    "scleroderma",
    "hirsutism",
    "open wound from surgical incision",
    "intertrigo (skin condition)",
    "hammer toe",
    "fungal infection of the hair",
    "tooth abscess",
    "atrophic skin condition",
    "open wound of the lip",
    "postoperative infection",
    "skin disorder",
    "psoriasis",
    "onychomycosis",
    "acne",
    "broken tooth",
    "multiple myeloma",
    "rosacea",
    "fracture of the facial bones",
    "contact dermatitis",
    "skin polyp",
    "scar",
    "athlete's foot",
    "sebaceous cyst",
    "seborrheic keratosis",
    "skin pigmentation disorder",
    "skin cancer",
    "callus",
    "hemangioma",
    "molluscum contagiosum",
    "melanoma",
    "open wound of the jaw"
]

cluster_20 = [
    "alopecia",
    "fungal infection of the skin",
    "seborrheic dermatitis",
    "cystic fibrosis",
    "thrombocytopenia",
    "acanthosis nigricans",
    "eczema"
]

cluster_21 = [
    "hashimoto thyroiditis",
    "obesity",
    "myoclonus",
    "hypothyroidism",
    "diabetes",
    "alcoholic liver disease"
]

cluster_22 = [
    "dengue fever",
    "open wound of the cheek",
    "rheumatoid arthritis",
    "flu",
    "mumps",
    "sialoadenitis",
    "lymphogranuloma venereum"
]

cluster_23 = [
    "herpangina",
    "gum disease",
    "wilson disease",
    "hemophilia",
    "hyperosmotic hyperketotic state",
    "tooth disorder",
    "spherocytosis",
    "vulvar cancer",
    "thyroid cancer",
    "friedrich ataxia",
    "thalassemia",
    "histoplasmosis",
    "neurosis"
]

cluster_24 = [
    "von willebrand disease",
    "hypergammaglobulinemia",
    "diabetic kidney disease",
    "anal fistula",
    "hemorrhoids",
    "missed abortion"
]


cluster_25 = [
    "female infertility of unknown cause",
    "polycystic ovarian syndrome (pcos)"
]

cluster_26 = [
    "vitamin b12 deficiency",
    "metastatic cancer",
    "osteoporosis",
    "spina bifida"
]

cluster_27 = [
    "priapism",
    "bipolar disorder",
    "peyronie disease",
    "dislocation of the hip"
]

cluster_28 = [
    "pemphigus",
    "vitamin a deficiency",
    "chronic ulcer"
]


cluster_29 = [
    "stenosis of the tear duct",
    "foreign body in the eye"
]

cluster_30 = [
    "breast cancer",
    "fibrocystic breast disease",
    "breast cyst",
    "fibroadenoma"
]

cluster_31 = [
    "endometrial cancer"
]

cluster_32 = [
    "dental caries",
    "fracture of the jaw",
    "open wound of the ear",
    "open wound of the face"
]

cluster_33 = [
    "open wound due to trauma"
]

cluster_34 = [
    "systemic lupus erythematosis (sle)"
]

cluster_35 = [
    "arthritis of the hip",
    "reactive arthritis"
]

cluster_36 = [
    "meckel diverticulum"
]

cluster_37 = [
    "fracture of the foot"
]

cluster_38 = [
    "oppositional disorder",
    "adjustment reaction",
    "asperger syndrome"
]

cluster_39 = [
    "gestational diabetes"
]

cluster_40 = [
    "knee ligament or meniscus tear"
]

cluster_41 = [
    "human immunodeficiency virus infection (hiv)"
]

cluster_42 = [
    "pregnancy"
]

cluster_43 = [
    "scoliosis",
    "injury to the spinal cord"
]

cluster_44 = [
    "bladder obstruction"
]



# Define your symptom clusters and dictionaries here

cluster_dict = {1: cluster_1, 2: cluster_2, 3: cluster_3, 4: cluster_4, 5: cluster_5, 6: cluster_6, 7: cluster_7, 8: cluster_8, 9: cluster_9, 10: cluster_10, 11: cluster_11, 12: cluster_12, 13: cluster_13, 14: cluster_14, 15: cluster_15, 16: cluster_16, 17: cluster_17, 18: cluster_18, 19: cluster_19, 20: cluster_20, 21: cluster_21, 22: cluster_22, 23: cluster_23, 24: cluster_24, 25: cluster_25, 26: cluster_26, 27: cluster_27, 28: cluster_28, 29: cluster_29, 30: cluster_30, 31: cluster_31, 32: cluster_32, 33: cluster_33, 34: cluster_34, 35: cluster_35, 36: cluster_36, 37: cluster_37, 38: cluster_38, 39: cluster_39, 40: cluster_40, 41: cluster_41, 42: cluster_42, 43: cluster_43, 44: cluster_44}


symptoms = {
    "anxiety and nervousness": 0,
    "depression": 1,
    "shortness of breath": 2,
    "depressive or psychotic symptoms": 3,
    "sharp chest pain": 4,
    "dizziness": 5,
    "insomnia": 6,
    "abnormal involuntary movements": 7,
    "chest tightness": 8,
    "palpitations": 9,
    "irregular heartbeat": 10,
    "breathing fast": 11,
    "hoarse voice": 12,
    "sore throat": 13,
    "difficulty speaking": 14,
    "cough": 15,
    "nasal congestion": 16,
    "throat swelling": 17,
    "diminished hearing": 18,
    "lump in throat": 19,
    "throat feels tight": 20,
    "difficulty in swallowing": 21,
    "skin swelling": 22,
    "retention of urine": 23,
    "groin mass": 24,
    "leg pain": 25,
    "hip pain": 26,
    "suprapubic pain": 27,
    "blood in stool": 28,
    "lack of growth": 29,
    "emotional symptoms": 30,
    "elbow weakness": 31,
    "back weakness": 32,
    "pus in sputum": 33,
    "symptoms of the scrotum and testes": 34,
    "swelling of scrotum": 35,
    "pain in testicles": 36,
    "flatulence": 37,
    "pus draining from ear": 38,
    "jaundice": 39,
    "mass in scrotum": 40,
    "white discharge from eye": 41,
    "irritable infant": 42,
    "abusing alcohol": 43,
    "fainting": 44,
    "hostile behavior": 45,
    "drug abuse": 46,
    "sharp abdominal pain": 47,
    "feeling ill": 48,
    "vomiting": 49,
    "headache": 50,
    "nausea": 51,
    "diarrhea": 52,
    "vaginal itching": 53,
    "vaginal dryness": 54,
    "painful urination": 55,
    "involuntary urination": 56,
    "pain during intercourse": 57,
    "frequent urination": 58,
    "lower abdominal pain": 59,
    "vaginal discharge": 60,
    "blood in urine": 61,
    "hot flashes": 62,
    "intermenstrual bleeding": 63,
    "hand or finger pain": 64,
    "wrist pain": 65,
    "hand or finger swelling": 66,
    "arm pain": 67,
    "wrist swelling": 68,
    "arm stiffness or tightness": 69,
    "arm swelling": 70,
    "hand or finger stiffness or tightness": 71,
    "wrist stiffness or tightness": 72,
    "lip swelling": 73,
    "toothache": 74,
    "abnormal appearing skin": 75,
    "skin lesion": 76,
    "acne or pimples": 77,
    "dry lips": 78,
    "facial pain": 79,
    "mouth ulcer": 80,
    "skin growth": 81,
    "eye deviation": 82,
    "diminished vision": 83,
    "double vision": 84,
    "cross-eyed": 85,
    "symptoms of eye": 86,
    "pain in eye": 87,
    "eye moves abnormally": 88,
    "abnormal movement of eyelid": 89,
    "foreign body sensation in eye": 90,
    "irregular appearing scalp": 91,
    "swollen lymph nodes": 92,
    "back pain": 93,
    "neck pain": 94,
    "low back pain": 95,
    "pain of the anus": 96,
    "pain during pregnancy": 97,
    "pelvic pain": 98,
    "impotence": 99,
    "infant spitting up": 100,
    "vomiting blood": 101,
    "regurgitation": 102,
    "burning abdominal pain": 103,
    "restlessness": 104,
    "symptoms of infants": 105,
    "wheezing": 106,
    "peripheral edema": 107,
    "neck mass": 108,
    "ear pain": 109,
    "jaw swelling": 110,
    "mouth dryness": 111,
    "neck swelling": 112,
    "knee pain": 113,
    "foot or toe pain": 114,
    "bowlegged or knock-kneed": 115,
    "ankle pain": 116,
    "bones are painful": 117,
    "knee weakness": 118,
    "elbow pain": 119,
    "knee swelling": 120,
    "skin moles": 121,
    "knee lump or mass": 122,
    "weight gain": 123,
    "problems with movement": 124,
    "knee stiffness or tightness": 125,
    "leg swelling": 126,
    "foot or toe swelling": 127,
    "heartburn": 128,
    "smoking problems": 129,
    "muscle pain": 130,
    "infant feeding problem": 131,
    "recent weight loss": 132,
    "problems with shape or size of breast": 133,
    "underweight": 134,
    "difficulty eating": 135,
    "scanty menstrual flow": 136,
    "vaginal pain": 137,
    "vaginal redness": 138,
    "vulvar irritation": 139,
    "weakness": 140,
    "decreased heart rate": 141,
    "increased heart rate": 142,
    "bleeding or discharge from nipple": 143,
    "ringing in ear": 144,
    "plugged feeling in ear": 145,
    "itchy ear(s)": 146,
    "frontal headache": 147,
    "fluid in ear": 148,
    "neck stiffness or tightness": 149,
    "spots or clouds in vision": 150,
    "eye redness": 151,
    "lacrimation": 152,
    "itchiness of eye": 153,
    "blindness": 154,
    "eye burns or stings": 155,
    "itchy eyelid": 156,
    "feeling cold": 157,
    "decreased appetite": 158,
    "excessive appetite": 159,
    "excessive anger": 160,
    "loss of sensation": 161,
    "focal weakness": 162,
    "slurring words": 163,
    "symptoms of the face": 164,
    "disturbance of memory": 165,
    "paresthesia": 166,
    "side pain": 167,
    "fever": 168,
    "shoulder pain": 169,
    "shoulder stiffness or tightness": 170,
    "shoulder weakness": 171,
    "arm cramps or spasms": 172,
    "shoulder swelling": 173,
    "tongue lesions": 174,
    "leg cramps or spasms": 175,
    "abnormal appearing tongue": 176,
    "ache all over": 177,
    "lower body pain": 178,
    "problems during pregnancy": 179,
    "spotting or bleeding during pregnancy": 180,
    "cramps and spasms": 181,
    "upper abdominal pain": 182,
    "stomach bloating": 183,
    "changes in stool appearance": 184,
    "unusual color or odor to urine": 185,
    "kidney mass": 186,
    "swollen abdomen": 187,
    "symptoms of prostate": 188,
    "leg stiffness or tightness": 189,
    "difficulty breathing": 190,
    "rib pain": 191,
    "joint pain": 192,
    "muscle stiffness or tightness": 193,
    "pallor": 194,
    "hand or finger lump or mass": 195,
    "chills": 196,
    "groin pain": 197,
    "fatigue": 198,
    "abdominal distention": 199,
    "regurgitation.1": 200,
    "symptoms of the kidneys": 201,
    "melena": 202,
    "flushing": 203,
    "coughing up sputum": 204,
    "seizures": 205,
    "delusions or hallucinations": 206,
    "shoulder cramps or spasms": 207,
    "joint stiffness or tightness": 208,
    "pain or soreness of breast": 209,
    "excessive urination at night": 210,
    "bleeding from eye": 211,
    "rectal bleeding": 212,
    "constipation": 213,
    "temper problems": 214,
    "coryza": 215,
    "wrist weakness": 216,
    "eye strain": 217,
    "hemoptysis": 218,
    "lymphedema": 219,
    "skin on leg or foot looks infected": 220,
    "allergic reaction": 221,
    "congestion in chest": 222,
    "muscle swelling": 223,
    "pus in urine": 224,
    "abnormal size or shape of ear": 225,
    "low back weakness": 226,
    "sleepiness": 227,
    "apnea": 228,
    "abnormal breathing sounds": 229,
    "excessive growth": 230,
    "elbow cramps or spasms": 231,
    "feeling hot and cold": 232,
    "blood clots during menstrual periods": 233,
    "absence of menstruation": 234,
    "pulling at ears": 235,
    "gum pain": 236,
    "redness in ear": 237,
    "fluid retention": 238,
    "flu-like syndrome": 239,
    "sinus congestion": 240,
    "painful sinuses": 241,
    "fears and phobias": 242,
    "recent pregnancy": 243,
    "uterine contractions": 244,
    "burning chest pain": 245,
    "back cramps or spasms": 246,
    "stiffness all over": 247,
    "muscle cramps, contractures, or spasms": 248,
    "low back cramps or spasms": 249,
    "back mass or lump": 250,
    "nosebleed": 251,
    "long menstrual periods": 252,
    "heavy menstrual flow": 253,
    "unpredictable menstruation": 254,
    "painful menstruation": 255,
    "infertility": 256,
    "frequent menstruation": 257,
    "sweating": 258,
    "mass on eyelid": 259,
    "swollen eye": 260,
    "eyelid swelling": 261,
    "eyelid lesion or rash": 262,
    "unwanted hair": 263,
    "symptoms of bladder": 264,
    "irregular appearing nails": 265,
    "itching of skin": 266,
    "hurts to breath": 267,
    "nailbiting": 268,
    "skin dryness, peeling, scaliness, or roughness": 269,
    "skin on arm or hand looks infected": 270,
    "skin irritation": 271,
    "itchy scalp": 272,
    "hip swelling": 273,
    "incontinence of stool": 274,
    "foot or toe cramps or spasms": 275,
    "warts": 276,
    "bumps on penis": 277,
    "too little hair": 278,
    "foot or toe lump or mass": 279,
    "skin rash": 280,
    "mass or swelling around the anus": 281,
    "low back swelling": 282,
    "ankle swelling": 283,
    "hip lump or mass": 284,
    "drainage in throat": 285,
    "dry or flaky scalp": 286,
    "premenstrual tension or irritability": 287,
    "feeling hot": 288,
    "feet turned in": 289,
    "foot or toe stiffness or tightness": 290,
    "pelvic pressure": 291,
    "elbow swelling": 292,
    "elbow stiffness or tightness": 293,
    "early or late onset of menopause": 294,
    "mass on ear": 295,
    "bleeding from ear": 296,
    "hand or finger weakness": 297,
    "low self-esteem": 298,
    "throat irritation": 299,
    "itching of the anus": 300,
    "swollen or red tonsils": 301,
    "irregular belly button": 302,
    "swollen tongue": 303,
    "lip sore": 304,
    "vulvar sore": 305,
    "hip stiffness or tightness": 306,
    "mouth pain": 307,
    "arm weakness": 308,
    "leg lump or mass": 309,
    "disturbance of smell or taste": 310,
    "discharge in stools": 311,
    "penis pain": 312,
    "loss of sex drive": 313,
    "obsessions and compulsions": 314,
    "antisocial behavior": 315,
    "neck cramps or spasms": 316,
    "pupils unequal": 317,
    "poor circulation": 318,
    "thirst": 319,
    "sleepwalking": 320,
    "skin oiliness": 321,
    "sneezing": 322,
    "bladder mass": 323,
    "knee cramps or spasms": 324,
    "premature ejaculation": 325,
    "leg weakness": 326,
    "posture problems": 327,
    "bleeding in mouth": 328,
    "tongue bleeding": 329,
    "change in skin mole size or color": 330,
    "penis redness": 331,
    "penile discharge": 332,
    "shoulder lump or mass": 333,
    "polyuria": 334,
    "cloudy eye": 335,
    "hysterical behavior": 336,
    "arm lump or mass": 337,
    "nightmares": 338,
    "bleeding gums": 339,
    "pain in gums": 340,
    "bedwetting": 341,
    "diaper rash": 342,
    "lump or mass of breast": 343,
    "vaginal bleeding after menopause": 344,
    "infrequent menstruation": 345,
    "mass on vulva": 346,
    "jaw pain": 347,
    "itching of scrotum": 348,
    "postpartum problems of the breast": 349,
    "eyelid retracted": 350,
    "hesitancy": 351,
    "elbow lump or mass": 352,
    "muscle weakness": 353,
    "throat redness": 354,
    "joint swelling": 355,
    "tongue pain": 356,
    "redness in or around nose": 357,
    "wrinkles on skin": 358,
    "foot or toe weakness": 359,
    "hand or finger cramps or spasms": 360,
    "back stiffness or tightness": 361,
    "wrist lump or mass": 362,
    "skin pain": 363,
    "low back stiffness or tightness": 364,
    "low urine output": 365,
    "skin on head or neck looks infected": 366,
    "stuttering or stammering": 367,
    "problems with orgasm": 368,
    "nose deformity": 369,
    "lump over jaw": 370,
    "sore in nose": 371,
    "hip weakness": 372,
    "back swelling": 373,
    "ankle stiffness or tightness": 374,
    "ankle weakness": 375,
    "neck weakness": 376
}

model = joblib.load('Models/model.pkl')
jgb = joblib.load('Models/trained_model.pkl')


def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms))
    for item in patient_symptoms:
        if item in symptoms:
            input_vector[symptoms[item]] = 1
    return model.predict([input_vector])[0]

def predicted_value(patient_symptoms):
    input_vector1 = np.zeros(len(symptoms))
    for item in patient_symptoms:
        if item in symptoms:
            input_vector1[symptoms[item]] = 1
    return jgb.predict([input_vector1])[0]

# Define your Flask route for handling predictions
@app.route('/predicts', methods=['POST'])
def predict():
    if request.method == 'POST':
        symptoms_input = request.json['symptoms']
        user_symptoms = [s.strip() for s in symptoms_input.split(',')]
        user_symptoms = [sym.strip("[]' ") for sym in user_symptoms]

        predicted_cluster = get_predicted_value(user_symptoms)
        predicted_disease = cluster_dict.get(predicted_cluster, "Unknown Disease")

        predicted_disease_result = predicted_value(user_symptoms)

        return jsonify({'disease': predicted_disease, 'cluster': predicted_disease_result})


if __name__ == '__main__':
    app.run(debug=True, port=5001)