from flask import Flask, jsonify, render_template, request
import joblib
import numpy as np
from flask_cors import CORS
from flask_cors import CORS, cross_origin

app = Flask(__name__)
CORS(app, supports_credentials= True)
app.config["CORS_HEADERS"] = "Content-Type" #


# Load the saved model
model = joblib.load('Models/trained_model.pkl')

# Symptoms dictionary (as you provided)
symptoms = {
    "anxiety and nervousness": 0,
    "depression": 1,
    "shortness of breath": 2,
    "depressive or psychotic symptoms": 3,
    "sharp chest pain": 4,
    "dizziness": 5,
    "insomnia": 6,
    "abnormal involuntary movements": 7,
    "chest tightness": 8,
    "palpitations": 9,
    "irregular heartbeat": 10,
    "breathing fast": 11,
    "hoarse voice": 12,
    "sore throat": 13,
    "difficulty speaking": 14,
    "cough": 15,
    "nasal congestion": 16,
    "throat swelling": 17,
    "diminished hearing": 18,
    "lump in throat": 19,
    "throat feels tight": 20,
    "difficulty in swallowing": 21,
    "skin swelling": 22,
    "retention of urine": 23,
    "groin mass": 24,
    "leg pain": 25,
    "hip pain": 26,
    "suprapubic pain": 27,
    "blood in stool": 28,
    "lack of growth": 29,
    "emotional symptoms": 30,
    "elbow weakness": 31,
    "back weakness": 32,
    "pus in sputum": 33,
    "symptoms of the scrotum and testes": 34,
    "swelling of scrotum": 35,
    "pain in testicles": 36,
    "flatulence": 37,
    "pus draining from ear": 38,
    "jaundice": 39,
    "mass in scrotum": 40,
    "white discharge from eye": 41,
    "irritable infant": 42,
    "abusing alcohol": 43,
    "fainting": 44,
    "hostile behavior": 45,
    "drug abuse": 46,
    "sharp abdominal pain": 47,
    "feeling ill": 48,
    "vomiting": 49,
    "headache": 50,
    "nausea": 51,
    "diarrhea": 52,
    "vaginal itching": 53,
    "vaginal dryness": 54,
    "painful urination": 55,
    "involuntary urination": 56,
    "pain during intercourse": 57,
    "frequent urination": 58,
    "lower abdominal pain": 59,
    "vaginal discharge": 60,
    "blood in urine": 61,
    "hot flashes": 62,
    "intermenstrual bleeding": 63,
    "hand or finger pain": 64,
    "wrist pain": 65,
    "hand or finger swelling": 66,
    "arm pain": 67,
    "wrist swelling": 68,
    "arm stiffness or tightness": 69,
    "arm swelling": 70,
    "hand or finger stiffness or tightness": 71,
    "wrist stiffness or tightness": 72,
    "lip swelling": 73,
    "toothache": 74,
    "abnormal appearing skin": 75,
    "skin lesion": 76,
    "acne or pimples": 77,
    "dry lips": 78,
    "facial pain": 79,
    "mouth ulcer": 80,
    "skin growth": 81,
    "eye deviation": 82,
    "diminished vision": 83,
    "double vision": 84,
    "cross-eyed": 85,
    "symptoms of eye": 86,
    "pain in eye": 87,
    "eye moves abnormally": 88,
    "abnormal movement of eyelid": 89,
    "foreign body sensation in eye": 90,
    "irregular appearing scalp": 91,
    "swollen lymph nodes": 92,
    "back pain": 93,
    "neck pain": 94,
    "low back pain": 95,
    "pain of the anus": 96,
    "pain during pregnancy": 97,
    "pelvic pain": 98,
    "impotence": 99,
    "infant spitting up": 100,
    "vomiting blood": 101,
    "regurgitation": 102,
    "burning abdominal pain": 103,
    "restlessness": 104,
    "symptoms of infants": 105,
    "wheezing": 106,
    "peripheral edema": 107,
    "neck mass": 108,
    "ear pain": 109,
    "jaw swelling": 110,
    "mouth dryness": 111,
    "neck swelling": 112,
    "knee pain": 113,
    "foot or toe pain": 114,
    "bowlegged or knock-kneed": 115,
    "ankle pain": 116,
    "bones are painful": 117,
    "knee weakness": 118,
    "elbow pain": 119,
    "knee swelling": 120,
    "skin moles": 121,
    "knee lump or mass": 122,
    "weight gain": 123,
    "problems with movement": 124,
    "knee stiffness or tightness": 125,
    "leg swelling": 126,
    "foot or toe swelling": 127,
    "heartburn": 128,
    "smoking problems": 129,
    "muscle pain": 130,
    "infant feeding problem": 131,
    "recent weight loss": 132,
    "problems with shape or size of breast": 133,
    "underweight": 134,
    "difficulty eating": 135,
    "scanty menstrual flow": 136,
    "vaginal pain": 137,
    "vaginal redness": 138,
    "vulvar irritation": 139,
    "weakness": 140,
    "decreased heart rate": 141,
    "increased heart rate": 142,
    "bleeding or discharge from nipple": 143,
    "ringing in ear": 144,
    "plugged feeling in ear": 145,
    "itchy ear(s)": 146,
    "frontal headache": 147,
    "fluid in ear": 148,
    "neck stiffness or tightness": 149,
    "spots or clouds in vision": 150,
    "eye redness": 151,
    "lacrimation": 152,
    "itchiness of eye": 153,
    "blindness": 154,
    "eye burns or stings": 155,
    "itchy eyelid": 156,
    "feeling cold": 157,
    "decreased appetite": 158,
    "excessive appetite": 159,
    "excessive anger": 160,
    "loss of sensation": 161,
    "focal weakness": 162,
    "slurring words": 163,
    "symptoms of the face": 164,
    "disturbance of memory": 165,
    "paresthesia": 166,
    "side pain": 167,
    "fever": 168,
    "shoulder pain": 169,
    "shoulder stiffness or tightness": 170,
    "shoulder weakness": 171,
    "arm cramps or spasms": 172,
    "shoulder swelling": 173,
    "tongue lesions": 174,
    "leg cramps or spasms": 175,
    "abnormal appearing tongue": 176,
    "ache all over": 177,
    "lower body pain": 178,
    "problems during pregnancy": 179,
    "spotting or bleeding during pregnancy": 180,
    "cramps and spasms": 181,
    "upper abdominal pain": 182,
    "stomach bloating": 183,
    "changes in stool appearance": 184,
    "unusual color or odor to urine": 185,
    "kidney mass": 186,
    "swollen abdomen": 187,
    "symptoms of prostate": 188,
    "leg stiffness or tightness": 189,
    "difficulty breathing": 190,
    "rib pain": 191,
    "joint pain": 192,
    "muscle stiffness or tightness": 193,
    "pallor": 194,
    "hand or finger lump or mass": 195,
    "chills": 196,
    "groin pain": 197,
    "fatigue": 198,
    "abdominal distention": 199,
    "regurgitation.1": 200,
    "symptoms of the kidneys": 201,
    "melena": 202,
    "flushing": 203,
    "coughing up sputum": 204,
    "seizures": 205,
    "delusions or hallucinations": 206,
    "shoulder cramps or spasms": 207,
    "joint stiffness or tightness": 208,
    "pain or soreness of breast": 209,
    "excessive urination at night": 210,
    "bleeding from eye": 211,
    "rectal bleeding": 212,
    "constipation": 213,
    "temper problems": 214,
    "coryza": 215,
    "wrist weakness": 216,
    "eye strain": 217,
    "hemoptysis": 218,
    "lymphedema": 219,
    "skin on leg or foot looks infected": 220,
    "allergic reaction": 221,
    "congestion in chest": 222,
    "muscle swelling": 223,
    "pus in urine": 224,
    "abnormal size or shape of ear": 225,
    "low back weakness": 226,
    "sleepiness": 227,
    "apnea": 228,
    "abnormal breathing sounds": 229,
    "excessive growth": 230,
    "elbow cramps or spasms": 231,
    "feeling hot and cold": 232,
    "blood clots during menstrual periods": 233,
    "absence of menstruation": 234,
    "pulling at ears": 235,
    "gum pain": 236,
    "redness in ear": 237,
    "fluid retention": 238,
    "flu-like syndrome": 239,
    "sinus congestion": 240,
    "painful sinuses": 241,
    "fears and phobias": 242,
    "recent pregnancy": 243,
    "uterine contractions": 244,
    "burning chest pain": 245,
    "back cramps or spasms": 246,
    "stiffness all over": 247,
    "muscle cramps, contractures, or spasms": 248,
    "low back cramps or spasms": 249,
    "back mass or lump": 250,
    "nosebleed": 251,
    "long menstrual periods": 252,
    "heavy menstrual flow": 253,
    "unpredictable menstruation": 254,
    "painful menstruation": 255,
    "infertility": 256,
    "frequent menstruation": 257,
    "sweating": 258,
    "mass on eyelid": 259,
    "swollen eye": 260,
    "eyelid swelling": 261,
    "eyelid lesion or rash": 262,
    "unwanted hair": 263,
    "symptoms of bladder": 264,
    "irregular appearing nails": 265,
    "itching of skin": 266,
    "hurts to breath": 267,
    "nailbiting": 268,
    "skin dryness, peeling, scaliness, or roughness": 269,
    "skin on arm or hand looks infected": 270,
    "skin irritation": 271,
    "itchy scalp": 272,
    "hip swelling": 273,
    "incontinence of stool": 274,
    "foot or toe cramps or spasms": 275,
    "warts": 276,
    "bumps on penis": 277,
    "too little hair": 278,
    "foot or toe lump or mass": 279,
    "skin rash": 280,
    "mass or swelling around the anus": 281,
    "low back swelling": 282,
    "ankle swelling": 283,
    "hip lump or mass": 284,
    "drainage in throat": 285,
    "dry or flaky scalp": 286,
    "premenstrual tension or irritability": 287,
    "feeling hot": 288,
    "feet turned in": 289,
    "foot or toe stiffness or tightness": 290,
    "pelvic pressure": 291,
    "elbow swelling": 292,
    "elbow stiffness or tightness": 293,
    "early or late onset of menopause": 294,
    "mass on ear": 295,
    "bleeding from ear": 296,
    "hand or finger weakness": 297,
    "low self-esteem": 298,
    "throat irritation": 299,
    "itching of the anus": 300,
    "swollen or red tonsils": 301,
    "irregular belly button": 302,
    "swollen tongue": 303,
    "lip sore": 304,
    "vulvar sore": 305,
    "hip stiffness or tightness": 306,
    "mouth pain": 307,
    "arm weakness": 308,
    "leg lump or mass": 309,
    "disturbance of smell or taste": 310,
    "discharge in stools": 311,
    "penis pain": 312,
    "loss of sex drive": 313,
    "obsessions and compulsions": 314,
    "antisocial behavior": 315,
    "neck cramps or spasms": 316,
    "pupils unequal": 317,
    "poor circulation": 318,
    "thirst": 319,
    "sleepwalking": 320,
    "skin oiliness": 321,
    "sneezing": 322,
    "bladder mass": 323,
    "knee cramps or spasms": 324,
    "premature ejaculation": 325,
    "leg weakness": 326,
    "posture problems": 327,
    "bleeding in mouth": 328,
    "tongue bleeding": 329,
    "change in skin mole size or color": 330,
    "penis redness": 331,
    "penile discharge": 332,
    "shoulder lump or mass": 333,
    "polyuria": 334,
    "cloudy eye": 335,
    "hysterical behavior": 336,
    "arm lump or mass": 337,
    "nightmares": 338,
    "bleeding gums": 339,
    "pain in gums": 340,
    "bedwetting": 341,
    "diaper rash": 342,
    "lump or mass of breast": 343,
    "vaginal bleeding after menopause": 344,
    "infrequent menstruation": 345,
    "mass on vulva": 346,
    "jaw pain": 347,
    "itching of scrotum": 348,
    "postpartum problems of the breast": 349,
    "eyelid retracted": 350,
    "hesitancy": 351,
    "elbow lump or mass": 352,
    "muscle weakness": 353,
    "throat redness": 354,
    "joint swelling": 355,
    "tongue pain": 356,
    "redness in or around nose": 357,
    "wrinkles on skin": 358,
    "foot or toe weakness": 359,
    "hand or finger cramps or spasms": 360,
    "back stiffness or tightness": 361,
    "wrist lump or mass": 362,
    "skin pain": 363,
    "low back stiffness or tightness": 364,
    "low urine output": 365,
    "skin on head or neck looks infected": 366,
    "stuttering or stammering": 367,
    "problems with orgasm": 368,
    "nose deformity": 369,
    "lump over jaw": 370,
    "sore in nose": 371,
    "hip weakness": 372,
    "back swelling": 373,
    "ankle stiffness or tightness": 374,
    "ankle weakness": 375,
    "neck weakness": 376
}


# Function to get predicted disease
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms))

    for item in patient_symptoms:
        input_vector[symptoms[item]] = 1
    return model.predict([input_vector])[0]

# Route for home page
# @app.route('/')
# def index():
#     return render_template('index.html')

# Route to handle form submission and display result
@app.route('/predict', methods=['POST'])
@cross_origin()
def predict():
      if request.method == 'POST':
        # Get symptoms from the form
        data = request.get_json()
        symptoms_input = data.get('symptoms')
        user_symptoms = [s.strip() for s in symptoms_input.split(',')]
        user_symptoms = [sym.strip("[]' ") for sym in user_symptoms]

        # Get predicted disease
        predicted_disease = get_predicted_value(user_symptoms)

        # Return the result as JSON
        return jsonify({'disease': predicted_disease})

if __name__ == '__main__':
    app.run(debug=True)
